# Generated by Django 5.2 on 2025-05-06 04:58

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsuleitem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.get_audio_path),
        ),
    ]
