# Generated by Django 5.2 on 2025-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_capsuleitem_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsuleitem',
            name='audio',
        ),
        migrations.AlterField(
            model_name='capsuleitem',
            name='item_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link'), ('video', 'Video')], max_length=10),
        ),
    ]
